[project]
name = "fintools"
version = "0.1.0"
description = "My finance tool poc"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "backtesting>=0.6.6",
    "ckdl>=1.0",
    "click>=8.5.0",
    "dependency-injector>=4.49.1",
    "duckdb>=1.5.5",
    "isodate>=0.7.2",
    "loguru>=0.7.3",
    "pandas>=3.0.5",
    "pandas-stubs>=3.0.5.260730",
    "pandera[full,polars]>=0.33.0",
    "pendulum>=3.2.0",
    "polars[lazy]>=1.44.1",
    "pyarrow>=25.0.1",
    "pytzdata>=2020.1",
    "pyyaml>=6.0.3",
    "seaborn>=0.13.2",
    "ta>=0.11.0",
    "yfinance>=1.7.0",
]

[build-system]
requires = ["uv_build>=0.12.6,<0.13"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-name = "fintools"
module-root = ""

[tool.setuptools.package-data]
fintools = ['fintools/*']
