# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: '3'

vars:
  DB_FILE: "{{.TASKFILE_DIR}}/data/fintools.duckdb"
  REF_FILE: "{{.TASKFILE_DIR}}/data/reference.yaml"
  LOG_LEVEL: "INFO"
env:
  FINTOOLS_DB_FILE: "{{.DB_FILE}}"
  FINTOOLS_REF_FILE: "{{.REF_FILE}}"
  LOGURU_LEVEL: "{{.LOG_LEVEL}}"
tasks:
  data:fetch:
    desc: "Get historical data"
    cmds:
      - |
        uv run fintools/scripts/fetch.py
    silent: false


  duckdb:ui:
    desc: Install and launch duckdb ui.
    cmds:
      - |
        echo "You will have to exit the process with ctrl+d to close the ui."
        duckdb -cmd "INSTALL ui; LOAD ui; CALL start_ui();" {{.DB_FILE}}
    silent: false
